import{javascript}from'@codemirror/lang-javascript';
import{python}from'@codemirror/lang-python';
import{rust}from'@codemirror/lang-rust';
import{java}from'@codemirror/lang-java';
import{go}from'@codemirror/lang-go';
import{cpp}from'@codemirror/lang-cpp';
import{html}from'@codemirror/lang-html';
import{css}from'@codemirror/lang-css';
import{json}from'@codemirror/lang-json';
import{sql}from'@codemirror/lang-sql';
import{php}from'@codemirror/lang-php';

export const LANGUAGES={
js:{label:'JavaScript',ext:()=>javascript({jsx:false})},
jsx:{label:'JSX',ext:()=>javascript({jsx:true})},
ts:{label:'TypeScript',ext:()=>javascript({typescript:true})},
tsx:{label:'TSX',ext:()=>javascript({jsx:true,typescript:true})},
python:{label:'Python',ext:python},
rust:{label:'Rust',ext:rust},
java:{label:'Java',ext:java},
go:{label:'Go',ext:go},
cpp:{label:'C++',ext:cpp},
html:{label:'HTML',ext:html},
css:{label:'CSS',ext:css},
json:{label:'JSON',ext:json},
sql:{label:'SQL',ext:sql},
php:{label:'PHP',ext:()=>php({plain:true})},
bash:{label:'Bash',ext:()=>null},
};
